$(document).ready(function() {
	$(".contact li").mouseover(function (){
		$(this).stop(true);
		$(this).clearQueue();
		$(this).animate({paddingLeft : 128}, 105);
	});
	$(".contact li").mouseout(function (){
		$(this).animate({paddingLeft : 0}, 150);
	});			$("#sportsbook-sub").css("display","none");	$("#sportsbook, #sportsbook-sub").hover(function() {		$("#sportsbook-sub").css("height","auto");		$("#sportsbook-sub").css("display","block");	},function() {		$("#sportsbook-sub").css("height","auto");		$("#sportsbook-sub").css("display","none");	});	$("#casino-sub").css("display","none");	$("#casino, #casino-sub").hover(function() {		$("#casino-sub").css("height","auto");		$("#casino-sub").css("display","block");	},function() {		$("#casino-sub").css("height","auto");		$("#casino-sub").css("display","none");	});	$("#poker-sub").css("display","none");	$("#poker, #poker-sub").hover(function() {		$("#poker-sub").css("height","auto");		$("#poker-sub").css("display","block");	},function() {		$("#poker-sub").css("height","auto");		$("#poker-sub").css("display","none");	});	$("#tangkas-sub").css("display","none");	$("#tangkas, #tangkas-sub").hover(function() {		$("#tangkas-sub").css("height","auto");		$("#tangkas-sub").css("display","block");	},function() {		$("#tangkas-sub").css("height","auto");		$("#tangkas-sub").css("display","none");	});$("#sportsbook-sub").css("display","none");	$("#sportsbook, #sportsbook-sub").hover(function() {		$("#sportsbook-sub").css("height","auto");		$("#sportsbook-sub").css("display","block");	},function() {		$("#sportsbook-sub").css("height","auto");		$("#sportsbook-sub").css("display","none");	});	$("#casino-sub").css("display","none");	$("#casino, #casino-sub").hover(function() {		$("#casino-sub").css("height","auto");		$("#casino-sub").css("display","block");	},function() {		$("#casino-sub").css("height","auto");		$("#casino-sub").css("display","none");	});	$("#poker-sub").css("display","none");	$("#poker, #poker-sub").hover(function() {		$("#poker-sub").css("height","auto");		$("#poker-sub").css("display","block");	},function() {		$("#poker-sub").css("height","auto");		$("#poker-sub").css("display","none");	});	$("#tangkas-sub").css("display","none");	$("#tangkas, #tangkas-sub").hover(function() {		$("#tangkas-sub").css("height","auto");		$("#tangkas-sub").css("display","block");	},function() {		$("#tangkas-sub").css("height","auto");		$("#tangkas-sub").css("display","none");	});
});
